---
title: "About"
sidebar: false
---

I am currently a Senior Research Fellow at the Institute for Environmental Design & Engineering at University College London. 

### Research Interests

- Soundscape Engineering
- Machine Learning
- Data Science
- Environmental Acoustics
- Psychoacoustics

## Education

::: {.d-flex .justify-content-between}
::: {}
**University College London**   
PhD in Environmental Acoustics and Machine Learning     
Supervisor: Prof Jian Kang      
Co-Superverisor: Dr. Phil Symonds   
:::
::: {.text-end}
London, UK  
Granted September 2022  
:::
:::
- Thesis: *Predictive Modelling of Complex Urban Soundscapes: Enabling an Engineering Approach to Soundscape Design*

::: {.d-flex .justify-content-between}
::: {}
**Cardiff University**  
BSc. (Hons) in Physics & Music  
:::
::: {.text-end}
Cardiff, Wales, UK      
Granted August 2015
:::
:::
- Dissertation: *The Physics of the Trombone Mouthpiece*

## Experience

::: {.d-flex .justify-content-between}
::: {}
**University College London**
:::
::: {.text-end}
October 2023 - present
:::
:::
*Senior Research Fellow in Soundscape Modelling*

- Supervisor: Prof Jian Kang

::: {.d-flex .justify-content-between}
::: {}
**University College London**, Institute for Environmental Design & Engineering
:::
::: {.text-end}
June 2022 - Oct 2023
:::
:::
*Research Fellow in Soundscape Modelling*

- Supervisor: Prof Jian Kang

::: {.d-flex .justify-content-between}
::: {}
**The Alan Turing Institute**, British Library, London, UK
:::
::: {.text-end}
May 2022 - March 2023
:::
:::
*Academic PI and Challenge Owner*

Funded by a UCL Health of the Public small grant, the DeLTA project aims to develop deep learning methods (specifically, a Temporal Convolutional Neural Network) for predicting annoyance
perception of various urban sounds. The Turing Data Study Group is an extension to this project carried out in partnership with the Alan Turing Institute.

- Coordinating a 5-day intensive collaborative hackathon hosted by the Turing Institute
- Prepare two large-scale datasets and define an open-ended challenge for the AI and data science experts recruited to participate in the DSG
- Lead the DSG and supervise the preparation of an openly-published report and prototype model for real-world application

::: {.d-flex .justify-content-between}
::: {}
**Hoare Lea, LLC**, London, UK
:::
::: {.text-end}
June 2019 - March 2021
:::
:::
*Acoustics Engineer / Soundscape Consultant*

- Academic/industry collaboration to design an IoT-based soundscape assessment tool

::: {.d-flex .justify-content-between}
::: {}
**Newson Brown Acoustics**, Santa Monica, CA  
:::
::: {.text-end}
June 2016 - September 2018
:::
:::
*Acoustical Consultant*

- Architectural acoustics, room acoustics modelling, & noise control

::: {.d-flex .justify-content-between}
::: {}
**Hayes McKenzie Partnership**, Machynlleth, Wales
:::
::: {.text-end}
July 2015 - April 2016
:::
:::
*Junior Acoustics Consultant*

::: {.d-flex .justify-content-between}
::: {}
**Busch Gardens Williamsburg**, Williamsburg, VA
:::
::: {.text-end}
Summer 2012
:::
:::
*Bass Trombonist*

## Associations

::: {.d-flex .justify-content-between}
::: {}
Member, **Acoustical Society of America**
:::
::: {.text-end}
2023 - Present
:::
:::

::: {.d-flex .justify-content-between}
::: {}
Associate Member, **Acoustical Society of America**
:::
::: {.text-end}
2016 - 2023
:::
:::

::: {.d-flex .justify-content-between}
::: {}
Student Member, **Institute of Acoustics**
:::
::: {.text-end}
2015 - Present
:::
:::

::: {.d-flex .justify-content-between}
::: {}
Researcher & Advisory Board Member, **International Misophonia Research Network (IMRN)**
:::
::: {.text-end}
2018 - 2022
:::
:::


<!-- ### Teaching

#### Facebook
::: {.d-flex .justify-content-between}
::: {}
Internal datacamp class on designing and analyzing experiments 
:::
::: {.text-end}
2017-2019
:::
:::

#### NYU Undergraduate
::: {.d-flex .justify-content-between}
::: {}
TA for Power and Politics in America (under Jonathan Nagler)
:::
::: {.text-end}
Fall 2014
:::
:::

::: {.d-flex .justify-content-between}
::: {}
TA for Games, Strategy and Politics (under Steven Brams)
:::
::: {.text-end}
Fall 2013
:::
:::

#### NYU Graduate

::: {.d-flex .justify-content-between}
::: {}
TA for Quantitative Methods II (under Nathaniel Beck)
:::
::: {.text-end}
Spring 2015
:::
:::

::: {.d-flex .justify-content-between}
::: {}
TA for Quantitative Methods II (under Cyrus Samii)
:::
::: {.text-end}
Spring 2014
:::
:::

::: {.d-flex .justify-content-between}
::: {}
High Performance Computing Talk for NYU Datalab
:::
::: {.text-end}
February 2014
:::
:::

::: {.d-flex .justify-content-between}
::: {}
Introduction to R for NYU Datalab
:::
::: {.text-end}
January 2013
:::
::: -->
